spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    #开启ACK
#    listener:
#      direct:
#        acknowledge-mode: manual
#        retry:
#          enabled: true
#          max-attempts: 3
#          initial-interval: 5000ms
#        default-requeue-rejected: true
#
#      simple:
#        acknowledge-mode: manual
#    # 开启发送确认
#    publisher-confirms: true
#    #开启发送失败退回
#    publisher-returns: true


  application:
    name: rabbitmq-sending
  thymeleaf:
    prefix: classpath:/templates/
    cache: false