spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    #开启ACK
    listener:
      direct:
        acknowledge-mode: manual
      simple:
        acknowledge-mode: manual
    # 开启发送确认
    publisher-confirms: true
    #开启发送失败退回
    publisher-returns: true
  application:
    name: rabbitmq-sending

server:
  port: 8089